# https://github.com/openai/codex/blob/main/docs/config.md

model_reasoning_effort = "medium"

[tools]
web_search = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[projects."/Users/masutaka/src/github.com/masutaka/masutaka.net"]
trust_level = "trusted"
