onboarding = false

[experimental]
switch_ascii_input_source_in_prefix = true

[keys]
prefix = "ctrl+z"

detach = "prefix+d"

new_workspace = "prefix+shift+c"
previous_workspace = "prefix+shift+p"
next_workspace = "prefix+shift+n"
switch_workspace = "prefix+shift+1..9"

new_tab = "prefix+ctrl+c"
previous_tab = "prefix+ctrl+p"
next_tab = "prefix+ctrl+n"

[[keys.command]]
key = "prefix+ctrl+space"
type = "plugin_action"
command = "beyondlex.herdr-recent-navigator.focus-previous-tab"
description = "Jump to previous tab"

[theme]
name = "gruvbox"

[ui]
prompt_new_tab_name = false
tab_bar_position = "bottom"

[ui.toast]
delivery = "system"
