#!/usr/bin/env zsh

echo "[pre-install] Installing ruby $1"

export RUBY_CONFIGURE_OPTS='--disable-install-doc'

if [ $(uname) = 'Darwin' ]; then
  RUBY_CONFIGURE_OPTS="$RUBY_CONFIGURE_OPTS --with-readline-dir=/usr"
fi

export RUBY_BUILD_OPTS='--verbose'

echo "[pre-install] Configure options: $RUBY_CONFIGURE_OPTS"
echo "[pre-install] ruby-build options: $RUBY_BUILD_OPTS"
