#!/usr/bin/env zsh

echo "[pre-install] Installing ruby $1"

export RUBY_CONFIGURE_OPTS='--disable-install-doc'

if [ $(uname) = 'Darwin' ]; then
  RUBY_CONFIGURE_OPTS="$RUBY_CONFIGURE_OPTS --with-readline-dir=/usr --with-libyaml-dir=$(brew --prefix libyaml)"
fi

echo "[pre-install] Configure options: $RUBY_CONFIGURE_OPTS"
